GENESIS_TIME: 1704085200
NUM_VALIDATORS: 3
GENESIS_VALIDATORS:
- 0x1c7fc215c289710fb3f7bd1770ffa9514eafa94a7c4c13596da1fe6b47d1ee058f245138d6ee5315b7f5660bf73475199b046843
- 0xeedf39399a2b7860a4167d13a60fdf223767f10f8dd657033b20b25f831af36029154f6d31b5b708f404ff5cf1db492b16a8af1d
- 0xf2d5c9236d81573cdd8512522f2fd82acdd79157574a1b6f487b670bae1d0a669bb104629558071590ce9a434f05ef3cf3ff9564
